"""empty message

Revision ID: 676c8a9e1b6c
Revises: 43dfc043b677
Create Date: 2023-11-07 11:47:42.095798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676c8a9e1b6c'
down_revision = '43dfc043b677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
